# https://github.com/Platane/Platane/blob/master/.github/workflows/main.yml

name: Generate Snake

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: heiemooa
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # - name: Push to GitHub
      #   uses: EndBug/add-and-commit@v7.2.1
      #   with:
      #     branch: main
      #     message: "Generate Contribution Snake"

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
